/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyRegistrationsRouteImport } from './routes/my-registrations'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as RegistrationEventIdRouteImport } from './routes/registration.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRegistrationsRoute = MyRegistrationsRouteImport.update({
  id: '/my-registrations',
  path: '/my-registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationEventIdRoute = RegistrationEventIdRouteImport.update({
  id: '/registration/$eventId',
  path: '/registration/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/registration/$eventId': typeof RegistrationEventIdRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/registration/$eventId': typeof RegistrationEventIdRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/my-registrations': typeof MyRegistrationsRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/registration/$eventId': typeof RegistrationEventIdRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/login'
    | '/my-registrations'
    | '/signup'
    | '/events/$eventId'
    | '/registration/$eventId'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/login'
    | '/my-registrations'
    | '/signup'
    | '/events/$eventId'
    | '/registration/$eventId'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/login'
    | '/my-registrations'
    | '/signup'
    | '/events/$eventId'
    | '/registration/$eventId'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MyRegistrationsRoute: typeof MyRegistrationsRoute
  SignupRoute: typeof SignupRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  RegistrationEventIdRoute: typeof RegistrationEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-registrations': {
      id: '/my-registrations'
      path: '/my-registrations'
      fullPath: '/my-registrations'
      preLoaderRoute: typeof MyRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/$eventId': {
      id: '/registration/$eventId'
      path: '/registration/$eventId'
      fullPath: '/registration/$eventId'
      preLoaderRoute: typeof RegistrationEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MyRegistrationsRoute: MyRegistrationsRoute,
  SignupRoute: SignupRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  RegistrationEventIdRoute: RegistrationEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
